"""HuggingFace Transformers predictor implementation.

Uses ``transformers.AutoModelForCausalLM`` and ``AutoTokenizer`` for
local inference.  Like the vLLM predictor, the tokenizer's
``apply_chat_template`` converts standardized messages and tool
definitions into a prompt string before generation.
"""

from __future__ import annotations

import json
from typing import Any

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer


class HuggingFacePredictor:
    """Predictor backed by HuggingFace Transformers.

    Args:
        model_name: HuggingFace model identifier
            (e.g. ``"HuggingFaceTB/SmolLM-135M-Instruct"``).
        device_map: Device placement strategy (``"auto"``, ``"cpu"``, …).
        max_new_tokens: Maximum number of new tokens to generate.
    """

    def __init__(
        self,
        model_name: str = "HuggingFaceTB/SmolLM-135M-Instruct",
        device_map: str = "auto",
        max_new_tokens: int = 256,
    ) -> None:
        self._tokenizer = AutoTokenizer.from_pretrained(model_name)
        self._model = AutoModelForCausalLM.from_pretrained(
            model_name,
            device_map=device_map,
            torch_dtype=torch.float32,
        )
        self._max_new_tokens = max_new_tokens

    async def generate(
        self,
        messages: list[dict[str, str]],
        tools: list[dict[str, Any]],
    ) -> dict[str, Any]:
        """Format messages via chat template and run HF generation.

        Args:
            messages: Chat messages in OpenAI format.
            tools: Tool definitions in OpenAI function-calling schema.

        Returns:
            Unified dict with either ``"type": "text"`` or
            ``"type": "tool_call"``.
        """
        template_kwargs: dict[str, Any] = {
            "tokenize": False,
            "add_generation_prompt": True,
        }
        if tools:
            template_kwargs["tools"] = tools

        prompt: str = self._tokenizer.apply_chat_template(
            messages, **template_kwargs
        )

        inputs = self._tokenizer(prompt, return_tensors="pt").to(
            self._model.device
        )

        with torch.no_grad():
            output_ids = self._model.generate(
                **inputs,
                max_new_tokens=self._max_new_tokens,
                do_sample=False,
            )

        # Decode only the newly generated tokens
        new_tokens = output_ids[0, inputs["input_ids"].shape[1] :]
        raw_text: str = self._tokenizer.decode(
            new_tokens, skip_special_tokens=True
        ).strip()

        return _parse_tool_call(raw_text)


def _parse_tool_call(text: str) -> dict[str, Any]:
    """Attempt to parse a tool call from raw model output.

    Args:
        text: Raw text generated by the model.

    Returns:
        Standardized response dict.
    """
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        try:
            parsed = json.loads(text[start : end + 1])
            tool_name = parsed.get("name") or parsed.get("tool_name", "")
            arguments = parsed.get("arguments") or parsed.get("parameters", {})
            if isinstance(arguments, str):
                try:
                    arguments = json.loads(arguments)
                except json.JSONDecodeError:
                    arguments = {}
            if tool_name:
                return {
                    "type": "tool_call",
                    "tool_name": tool_name,
                    "arguments": arguments,
                }
        except json.JSONDecodeError:
            pass

    return {"type": "text", "content": text}
