"""Shared parsing utilities for tool-calling predictors.

Provides a common :func:`parse_tool_call` helper used by the vLLM and
HuggingFace predictor implementations to extract tool calls from raw
model output.
"""

from __future__ import annotations

import json
from typing import Any


def parse_tool_call(text: str) -> dict[str, Any]:
    """Attempt to parse a tool call from raw model output.

    Tries to locate a JSON object containing ``"name"`` (or ``"tool_name"``)
    and ``"arguments"`` (or ``"parameters"``).  Falls back to a plain text
    response when parsing fails.

    Args:
        text: Raw text generated by the model.

    Returns:
        Standardized response dict with either ``"type": "tool_call"``
        or ``"type": "text"``.
    """
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        try:
            parsed = json.loads(text[start : end + 1])
            tool_name = parsed.get("name") or parsed.get("tool_name", "")
            arguments = parsed.get("arguments") or parsed.get("parameters", {})
            if isinstance(arguments, str):
                try:
                    arguments = json.loads(arguments)
                except json.JSONDecodeError:
                    arguments = {}
            if tool_name:
                return {
                    "type": "tool_call",
                    "tool_name": tool_name,
                    "arguments": arguments,
                }
        except json.JSONDecodeError:
            pass

    return {"type": "text", "content": text}
