version: "3.8"

services:
  devcontainer:
    # image: verlai/verl:vllm017.latest
    image: vllm/vllm-openai:v0.23.0
    network_mode: host
    shm_size: '128g'
    cap_add:
      - SYS_ADMIN
    runtime: nvidia
    environment:
      UV_CACHE_DIR:    /mnt/data1/uv-cache
      HF_HOME:         /mnt/data1/huggingface
      TORCH_HOME:      /mnt/data1/torch
      PIP_CACHE_DIR:   /mnt/data1/pip-cache
      WANDB_CACHE_DIR: /mnt/data1/wandb-cache
      TRITON_CACHE_DIR: /mnt/data1/triton-cache
    volumes:
      - ..:/workspaces/conversation2SQL:cached
      - ${HOME}/data:/workspaces/conversation2SQL/data
      - ${HF_HOME}:/mnt/data1/huggingface
      - ${UV_CACHE_DIR}:/mnt/data1/uv-cache
      - ${TORCH_HOME}:/mnt/data1/torch
      - ${PIP_CACHE_DIR}:/mnt/data1/pip-cache
      - ${WANDB_CACHE_DIR}:/mnt/data1/wandb-cache
      - ${TRITON_CACHE_DIR}:/mnt/data1/triton-cache
    depends_on:
      - postgresql
      - postgresql_full
    entrypoint: ["sleep", "infinity"]

  postgresql:
    image: shawnxxh/bird-interact-postgresql:latest
    container_name: bird_interact_postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123
      TZ: "Asia/Hong_Kong"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    command:
      - "-c"
      - "max_connections=300"
      - "-c"
      - "shared_buffers=256MB"
    ports:
      - "5432:5432"

  postgresql_full:
    image: shawnxxh/bird-interact-postgresql-full:latest
    container_name: bird_interact_postgresql_full
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123
      TZ: "Asia/Hong_Kong"
    volumes:
      - postgresql_data_full:/var/lib/postgresql/data
    command:
      - "-c"
      - "max_connections=300"
      - "-c"
      - "shared_buffers=256MB"
    ports:
      - "5433:5432"

volumes:
  postgresql_data:
  postgresql_data_full:
